### ISSUE TITLE
Create a DNS CNAME record on omegapoint.se

### ISSUE THREAD

**Issue by davisfreimanis** [Omegapoint/Kompassen-2.0#222]
Create a DNS CNAME record under omegapoint.se that points to kompassen2.azurewebsites.net for a more professional look

Suggestion: kompassen.omegapoint.se or kompassen2.omegapoint.se

I think Michael Westlund can help.

**Comment by victoriacatalan** [comment]
Michael Westlund has already been contacted about this! So it should be in progress, but I will poke him about it!
