### ISSUE TITLE
Create page for submitting KoKo lectures

### ISSUE THREAD

**Issue by Hannes-Samskog** [Omegapoint/Kompassen-2.0#249]

**Comment by jabbago** [comment]
- Key takeaway (textfält)
- Innehåll -> Beskrivning
- Pitch-video (länk eventuellt, ladda upp fil) Blob storage.
- läng på passet (20, 45 min, 90 min) - Kolla upp exakta värden
- komp dag flik försvinner 
- Sätt att delta försvinner 
- Förbereddelser(?)
-Typ av event  - Ws, föredrag, blixt, paneldisskussison.
