### ISSUE TITLE
KoKo lecture add lecturers from AD

### ISSUE THREAD

**Issue by Hannes-Samskog** [Omegapoint/Kompassen-2.0#266]
- [x] Add lecturer_lecture crosstable in backend 
- [x] Add graph api integration to add lecturers

**Comment by techbecca** [comment]
### Front-end
- [ ] display email for options
- [ ] store selected users in state
- [ ] display pre-selected lecturers (the current user) in the speaker list as fixed option
- [ ] filter away duplicates
