### ISSUE TITLE
Extract lecturers to excel

### ISSUE THREAD

**Issue by Hannes-Samskog** [Omegapoint/Kompassen-2.0#287]
- [ ] Name
- [ ] Email
- [ ] RookieStatus
- [ ] Talarbio
- [ ] Office
- [ ] Name of lecture/lecturers with status
- [ ] Link to image

**Comment by ipomega** [comment]
See this excel-file for how it used to look: 

https://omegapointcloud-my.sharepoint.com/:x:/g/personal/ida_petersson_omegapoint_se/EQQCU2E8oL1AphtkWA2oxqsBB9UVNfXFg8pHzXsOnF1SwA?e=mUxhzl
